%% init
% data=load('dataTrain.mat'); data=data.dataTrain;
datasetSelected={'Cubep','GehlerShi','gehlershi_and_cubep'};% datasetSelected{1,3}
indMethodSelect={[1 2 3 4 5 6 7 8],...
    [1 2 3 4 5 6 7],...
    [1 2 3 4 5 6 8],...
    [1 2 3 4 5 6],...
    [1 2 3 4 7 8],...
    [1 2 3 6 7],...
    [1 2 3 6 8],...
    [1 2 3 4],...
    [1 2 5 6],...
    [1 2 7 8]};
%% for table of selecting different unitary algorithm combination
for numRun=1:1
    for iDatSelected=[3] %3
        for iK1=2:2% 2
            for iK2=2:2 %4
                for jNumClu=[4] %[2 4 6]
                    for kEpochNum=[60] %[30 60 90]
                        for m_indMethod =1:10 %6
                            disp(['for the unitary algorithm combination: ', mat2str(indMethodSelect{1,m_indMethod}), ':'])
                            data.selecSet=datasetSelected{1,iDatSelected}; % GehlerShi,Cubep
                            % cmTr, featureTr,feat4Cheng,adjacentAngleError,illSet8TrNor; % log,rgb; indMethod = [1 2 7 8]; % auto
                            opt = genCNCOptions('k1',iK1,'k2',iK2,'method','rgb',...
                                'optimization',false,'NumClusters',jNumClu,'EpochNumber',kEpochNum,'InitialStepSize',0.01,...
                                'indMethod',indMethodSelect{1,m_indMethod},'cluster1Feature','featureTr','cluster2Feature','adjacentAngleError');
                            %
                            result = cluster2_anfis_cc(data,opt);
                            genResultXls(result,fullfile('results',[data.selecSet '.xlsx']));
                            genResultSelectAlgoTab(result,fullfile('results','SelectAlgoTabS2.xlsx'));
                            %fprintf('\n current: iterationNum=%s;\n iDatSelected=%s,\n  iK1=%s,\n iK2=%s, \n jNumClu=%s,\n kEpochNum=%s,\n  m_indMethod=%s\n',...
                            %    num2str(iDatSelected*iK1*iK2*length(m_indMethod)*length(kEpochNum)*length(jNumClu)),...
                            %    num2str(iDatSelected),num2str(iK1),num2str(iK2),num2str(jNumClu),num2str(kEpochNum),num2str(m_indMethod));
                        end
                    end
                end
            end
        end
    end
end
